### ISSUE TITLE
事物提交相关的

### ISSUE THREAD

**Issue by dingjun84** [killme2008/Metamorphosis#75]
假设一个极端情况：事物准备提交，调用msgStore.append()把message写入messageStore后，执行某一次AppendCallback.appendComplete时程序异常退出。这时消息已保存到数据文件，但是事物由于没有最终完成。

这种情况下事物在recover方法中回滚，已提交的message数据不会被回滚掉。

**Comment by yanfeipeng** [comment]
请问如果出现留存在系统中没有commit的消息后续是怎么处理的？
